Samples: # same names i.e. {Samples}_R1.fastq.gz and {Samples}_R2.fastq.gz
#    E100049712:
#    E100049712_L01_64:
#    E100049712_L01_97:
    E100049712_L01_98:
            #    E100049712_L01_99:
            #    E100049712_L01_101:
            #    E100049712_L01_102:
            #    E100049712_L01_103:
            #    E100049712_L01_104:

GENOMEREF: /QRISdata/Q1851/Prakrithi/refdata-gex-GRCh38-2020-A/fasta/genome.fa
REFGTF: /scratch/user/s4716765/TAR-scRNA-seq/from_fastqs/gencode.v43.chr_patch_hapl_scaff.annotation.gtf

SAMPWDIR: /scratch/project/stseq/Prakrithi/stomics # directory where summary information is stored
DATADIR:  /scratch/project/stseq/Prakrithi/stomics # directory where fastq files are stored
   
TMPDIR: /scratch/project/stseq/Prakrithi/stomics/temp

#PIPELINE_MAJOR: results_out # folder where scRNA-seq expression matrices are going to be stored
PIPELINE_MAJOR:  /scratch/project/stseq/Prakrithi/stomics

GLOBAL:
    allowed_mismatch: 10 # outFilterMismatchNmax parameter for STAR alignment
    BC_range: # barcode range
        first: 1
        last: 25
    UMI_range: # unique molecular identifier range
        first: 26
        last: 35 # 28 for v3, up to 26 for v2

PICARD: ~/.conda/envs/scTAR_cellranger/share/picard-2.23.8-0/picard.jar
DROPSEQ: ~/.conda/envs/scTAR_cellranger/share/dropseq_tools-2.4.0-1/
GTFTOGENEPRED: ~/.conda/envs/scTAR_cellranger/bin/gtfToGenePred # used to convert gtf to reFflat format, not needed if annotation is in reFflat
STAREXEC: ~/.conda/envs/scTAR_cellranger/bin/STAR
BLASTDB: /scratch/user/s4716765/BLAST_NCBI # path to where the nt BLAST database is stored
# full path of scripts folder
#FULLSCRIPTPATH: #/local/workdir/fw262/uTARAnalysisTool/HMM-scRNA-seq/testGitHub/scripts

CORES: 12 # how many cores to give for each process, snakemake automatically parallelize process using "snakemake -j {numTotalCores}" 
expectedCells: 5000
MERGEBP: 500
THRESH: 10000000
